/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package acchiappalatalpa;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author pazzagli.angelica
 */
public class FormGioco extends javax.swing.JFrame implements Runnable{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormGioco.class.getName());

    private ArrayList<Buca> buche;
    private Gestore gestore;
    private Talpa talpa;
    private Scambio scambio;
    private JButton[] bottoni;
    private Thread threadForm;
    
    public FormGioco() {
        initComponents();
        
        bottoni = new JButton[]{btnBuca1, btnBuca2, btnBuca3, btnBuca4, btnBuca5, btnBuca6};

        buche = new ArrayList<>();
        for(int i=0;i<6;i++) {
            buche.add(new Buca());
        }
        
        scambio = new Scambio(this);
        gestore = new Gestore(buche, scambio);
        talpa = new Talpa(gestore, scambio);
        talpa.start();

        threadForm = new Thread(this);
        threadForm.start();
    }
    
    public void mostraTalpa(int indice){
        ImageIcon talpa = new ImageIcon(getClass().getResource("/images/talpa.jfif"));
        bottoni[indice].setIcon(talpa);
    }

    public void nascondiTalpa(int indice){
        bottoni[indice].setIcon(null);
    }
    
    public void aggiornaPunteggio(int punteggio){
        lblPunteggio.setText(String.valueOf(punteggio));
    }
    
    @Override
    public void run() {
        while(true){
            try{
                Thread.sleep(100);
            }catch(Exception e){}
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBuca1 = new javax.swing.JButton();
        btnBuca6 = new javax.swing.JButton();
        btnBuca3 = new javax.swing.JButton();
        btnBuca2 = new javax.swing.JButton();
        btnBuca5 = new javax.swing.JButton();
        btnBuca4 = new javax.swing.JButton();
        lblTitPunteggio = new javax.swing.JLabel();
        lblPunteggio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setFont(new java.awt.Font("Serif", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ACCHIAPPA LA TALPA!");

        btnBuca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuca1ActionPerformed(evt);
            }
        });

        btnBuca6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuca6ActionPerformed(evt);
            }
        });

        btnBuca3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuca3ActionPerformed(evt);
            }
        });

        btnBuca2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuca2ActionPerformed(evt);
            }
        });

        btnBuca5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuca5ActionPerformed(evt);
            }
        });

        btnBuca4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuca4ActionPerformed(evt);
            }
        });

        lblTitPunteggio.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblTitPunteggio.setForeground(new java.awt.Color(255, 255, 255));
        lblTitPunteggio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitPunteggio.setText("PUNTEGGIO:");

        lblPunteggio.setFont(new java.awt.Font("Serif", 3, 18)); // NOI18N
        lblPunteggio.setForeground(new java.awt.Color(255, 255, 255));
        lblPunteggio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPunteggio.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuca4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuca1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuca5, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuca2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(101, 101, 101)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBuca3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnBuca6, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addComponent(lblTitPunteggio)
                        .addGap(28, 28, 28)
                        .addComponent(lblPunteggio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitPunteggio)
                    .addComponent(lblPunteggio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuca1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuca2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuca3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBuca4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuca5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuca6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuca1ActionPerformed
        gestore.colpisciBuca(0);
    }//GEN-LAST:event_btnBuca1ActionPerformed

    private void btnBuca2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuca2ActionPerformed
        gestore.colpisciBuca(1);
    }//GEN-LAST:event_btnBuca2ActionPerformed

    private void btnBuca3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuca3ActionPerformed
        gestore.colpisciBuca(2);
    }//GEN-LAST:event_btnBuca3ActionPerformed

    private void btnBuca4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuca4ActionPerformed
        gestore.colpisciBuca(3);
    }//GEN-LAST:event_btnBuca4ActionPerformed

    private void btnBuca5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuca5ActionPerformed
        gestore.colpisciBuca(4);
    }//GEN-LAST:event_btnBuca5ActionPerformed

    private void btnBuca6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuca6ActionPerformed
        gestore.colpisciBuca(5);
    }//GEN-LAST:event_btnBuca6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormGioco().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuca1;
    private javax.swing.JButton btnBuca2;
    private javax.swing.JButton btnBuca3;
    private javax.swing.JButton btnBuca4;
    private javax.swing.JButton btnBuca5;
    private javax.swing.JButton btnBuca6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPunteggio;
    private javax.swing.JLabel lblTitPunteggio;
    // End of variables declaration//GEN-END:variables
}
